version: "3.9"

services:
    database:
      image: postgres
      container_name: database-culinary-recipes
      restart: always
      ports: 
        - 1954:5432
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=UMONME68xjZdfzv6ZyoTPWDORjx3P8JLd+GnFNRKbDQ=
        - POSTGRES_DB=culinary_recipes
      volumes:
        - pgdata:/data/postgres
    
volumes:
  pgdata:
    driver: local
