name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
    
      - name: Run Docker Container Postgres
        run: docker-compose up -d

      - name: Run Migrations
        run: yarn migration

      - name: Up Memory Nodejs 4GB
        run: yarn upmemory

      - name: Run Tests
        run: yarn test
              
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/culinary_recipe"
